name: Build Windows EXE

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name "GeometryDashSongSwapper" main.py
        
    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: GeometryDashSongSwapper-exe
        path: dist/GeometryDashSongSwapper.exe
        
    - name: Upload to Release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/GeometryDashSongSwapper.exe
        asset_name: GeometryDashSongSwapper.exe
        asset_content_type: application/vnd.microsoft.portable-executable